server:
  port: 8190
  servlet:
    context-path: /content
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/media
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    hibernate:
      ddl-auto: update

#logging:
#  level:
#    org:
#      springframework: debug